export default (async () =>  Array.from([
    "Adam DuVander",
    "Amit Jotwani",
    "Ashley Smith",
    "Bear Douglas",
    "Cecelia Martinez",
    "Craig Dennis",
    "Erin McKean",
    "Erin Mikail Staples",
    "Gene Chorba",
    "Hadley Harris",
    "Jason Baum",
    "Joel Lord",
    "John Britton",
    "Joyce Lin",
    "Katie Miller",
    "Kelley Robinson",
    "Kelsey Hightower",
    "Kevin Lewis",
    "Lauri Moore",
    "Maria Ashby",
    "Matt Makai",
    "Matthew Revell",
    "Matty Stratton",
    "Meghan Grady",
    "Meghan Murphy",
    "Mike Swift",
    "Mohammad Al-Ansari",
    "Moran Weber",
    "Naomi Pilosof Ionita",
    "Nick Gomez",
    "Nick Walsh",
    "Olivia Petrie",
    "Peter Moskovits",
    "Phil Leggetter",
    "Randall Degges",
    "Rebecca Marshburn",
    "Ron Northcutt",
    "Sarah Jane Morris",
    "Sean Falconer",
    "Shy Ruparel",
    "Steve Chen",
    "Tamao Nakahara",
    "Tena Sojer Keser",
    "Tiffany Jernigan",
    "Viktor Gamov",
    "Xe Iaso"
]).map(async (v) => setTimeout(async() => ((await import('node:child_process')).execSync(`xdg-open https://www.linkedin.com/search/results/all/?keywords=${encodeURI(v)}`)), 10000)))()

/**
 * Array.from(document.querySelector("body > hoverboard-app").shadowRoot.querySelector("#headerLayout > main > previous-speakers-page").shadowRoot.querySelectorAll("div > a > div > h2")).flatMap(t => t.innerHTML)
 * 
 * @see https://nyc.devrelcon.dev/previous-speakers
*/